version: '3'
services:
  server:
    build: ./server
    environment:
    - webserver_port=3000
    ports:
     - "3000:8080"
    command: npm start
  clientservice:
    build: ./client
    depends_on:
     - "server"
    command: npm start