version: '3'
services:
  server1:
    build: ./server
    environment:
    - webserver_port=3000
    ports:
     - "3000:8080"
    command: npm start
  clientservice1:
    build: ./client
    depends_on:
     - "server1"
    command: npm start